/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SolidityTypes_pb = require('./SolidityTypes_pb.js');
goog.object.extend(proto, SolidityTypes_pb);
goog.exportSymbol('proto.TestRepeated', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TestRepeated = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.TestRepeated.repeatedFields_, null);
};
goog.inherits(proto.TestRepeated, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.TestRepeated.displayName = 'proto.TestRepeated';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.TestRepeated.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TestRepeated.prototype.toObject = function(opt_includeInstance) {
  return proto.TestRepeated.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TestRepeated} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TestRepeated.toObject = function(includeInstance, msg) {
  var f, obj = {
    stringField: jspb.Message.getFieldWithDefault(msg, 1, ""),
    uint256sList: jspb.Message.toObjectList(msg.getUint256sList(),
    SolidityTypes_pb.uint256.toObject, includeInstance),
    sint64sList: jspb.Message.toObjectList(msg.getSint64sList(),
    SolidityTypes_pb.int64.toObject, includeInstance),
    boolField: jspb.Message.getFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TestRepeated}
 */
proto.TestRepeated.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TestRepeated;
  return proto.TestRepeated.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TestRepeated} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TestRepeated}
 */
proto.TestRepeated.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringField(value);
      break;
    case 2:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.addUint256s(value);
      break;
    case 3:
      var value = new SolidityTypes_pb.int64;
      reader.readMessage(value,SolidityTypes_pb.int64.deserializeBinaryFromReader);
      msg.addSint64s(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolField(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TestRepeated.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TestRepeated.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TestRepeated} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TestRepeated.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStringField();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUint256sList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getSint64sList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      SolidityTypes_pb.int64.serializeBinaryToWriter
    );
  }
  f = message.getBoolField();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional string string_field = 1;
 * @return {string}
 */
proto.TestRepeated.prototype.getStringField = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.TestRepeated.prototype.setStringField = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated solidity.uint256 uint256s = 2;
 * @return {!Array<!proto.solidity.uint256>}
 */
proto.TestRepeated.prototype.getUint256sList = function() {
  return /** @type{!Array<!proto.solidity.uint256>} */ (
    jspb.Message.getRepeatedWrapperField(this, SolidityTypes_pb.uint256, 2));
};


/** @param {!Array<!proto.solidity.uint256>} value */
proto.TestRepeated.prototype.setUint256sList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.solidity.uint256=} opt_value
 * @param {number=} opt_index
 * @return {!proto.solidity.uint256}
 */
proto.TestRepeated.prototype.addUint256s = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.solidity.uint256, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.TestRepeated.prototype.clearUint256sList = function() {
  this.setUint256sList([]);
};


/**
 * repeated solidity.int64 sint64s = 3;
 * @return {!Array<!proto.solidity.int64>}
 */
proto.TestRepeated.prototype.getSint64sList = function() {
  return /** @type{!Array<!proto.solidity.int64>} */ (
    jspb.Message.getRepeatedWrapperField(this, SolidityTypes_pb.int64, 3));
};


/** @param {!Array<!proto.solidity.int64>} value */
proto.TestRepeated.prototype.setSint64sList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.solidity.int64=} opt_value
 * @param {number=} opt_index
 * @return {!proto.solidity.int64}
 */
proto.TestRepeated.prototype.addSint64s = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.solidity.int64, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.TestRepeated.prototype.clearSint64sList = function() {
  this.setSint64sList([]);
};


/**
 * optional bool bool_field = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.TestRepeated.prototype.getBoolField = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.TestRepeated.prototype.setBoolField = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};


goog.object.extend(exports, proto);
