/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SolidityTypes_pb = require('./SolidityTypes_pb.js');
goog.object.extend(proto, SolidityTypes_pb);
goog.exportSymbol('proto.TestInteger', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TestInteger = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.TestInteger, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.TestInteger.displayName = 'proto.TestInteger';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TestInteger.prototype.toObject = function(opt_includeInstance) {
  return proto.TestInteger.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TestInteger} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TestInteger.toObject = function(includeInstance, msg) {
  var f, obj = {
    sint32Field: jspb.Message.getFieldWithDefault(msg, 1, 0),
    int32Field: jspb.Message.getFieldWithDefault(msg, 2, 0),
    fixed32Field: jspb.Message.getFieldWithDefault(msg, 3, 0),
    fixed64Field: jspb.Message.getFieldWithDefault(msg, 4, 0),
    int256Field: (f = msg.getInt256Field()) && SolidityTypes_pb.int256.toObject(includeInstance, f),
    uint256Field: (f = msg.getUint256Field()) && SolidityTypes_pb.uint256.toObject(includeInstance, f),
    addressField: (f = msg.getAddressField()) && SolidityTypes_pb.address.toObject(includeInstance, f),
    int64Field: (f = msg.getInt64Field()) && SolidityTypes_pb.int64.toObject(includeInstance, f),
    uint64Field: (f = msg.getUint64Field()) && SolidityTypes_pb.uint64.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TestInteger}
 */
proto.TestInteger.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TestInteger;
  return proto.TestInteger.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TestInteger} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TestInteger}
 */
proto.TestInteger.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setSint32Field(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInt32Field(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFixed32());
      msg.setFixed32Field(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFixed64());
      msg.setFixed64Field(value);
      break;
    case 5:
      var value = new SolidityTypes_pb.int256;
      reader.readMessage(value,SolidityTypes_pb.int256.deserializeBinaryFromReader);
      msg.setInt256Field(value);
      break;
    case 6:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.setUint256Field(value);
      break;
    case 7:
      var value = new SolidityTypes_pb.address;
      reader.readMessage(value,SolidityTypes_pb.address.deserializeBinaryFromReader);
      msg.setAddressField(value);
      break;
    case 8:
      var value = new SolidityTypes_pb.int64;
      reader.readMessage(value,SolidityTypes_pb.int64.deserializeBinaryFromReader);
      msg.setInt64Field(value);
      break;
    case 9:
      var value = new SolidityTypes_pb.uint64;
      reader.readMessage(value,SolidityTypes_pb.uint64.deserializeBinaryFromReader);
      msg.setUint64Field(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TestInteger.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TestInteger.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TestInteger} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TestInteger.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSint32Field();
  if (f !== 0) {
    writer.writeSint32(
      1,
      f
    );
  }
  f = message.getInt32Field();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getFixed32Field();
  if (f !== 0) {
    writer.writeFixed32(
      3,
      f
    );
  }
  f = message.getFixed64Field();
  if (f !== 0) {
    writer.writeFixed64(
      4,
      f
    );
  }
  f = message.getInt256Field();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SolidityTypes_pb.int256.serializeBinaryToWriter
    );
  }
  f = message.getUint256Field();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
  f = message.getAddressField();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      SolidityTypes_pb.address.serializeBinaryToWriter
    );
  }
  f = message.getInt64Field();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      SolidityTypes_pb.int64.serializeBinaryToWriter
    );
  }
  f = message.getUint64Field();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      SolidityTypes_pb.uint64.serializeBinaryToWriter
    );
  }
};


/**
 * optional sint32 sint32_field = 1;
 * @return {number}
 */
proto.TestInteger.prototype.getSint32Field = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.TestInteger.prototype.setSint32Field = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 int32_field = 2;
 * @return {number}
 */
proto.TestInteger.prototype.getInt32Field = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.TestInteger.prototype.setInt32Field = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional fixed32 fixed32_field = 3;
 * @return {number}
 */
proto.TestInteger.prototype.getFixed32Field = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.TestInteger.prototype.setFixed32Field = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional fixed64 fixed64_field = 4;
 * @return {number}
 */
proto.TestInteger.prototype.getFixed64Field = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.TestInteger.prototype.setFixed64Field = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional solidity.int256 int256_field = 5;
 * @return {?proto.solidity.int256}
 */
proto.TestInteger.prototype.getInt256Field = function() {
  return /** @type{?proto.solidity.int256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.int256, 5));
};


/** @param {?proto.solidity.int256|undefined} value */
proto.TestInteger.prototype.setInt256Field = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.TestInteger.prototype.clearInt256Field = function() {
  this.setInt256Field(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.TestInteger.prototype.hasInt256Field = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional solidity.uint256 uint256_field = 6;
 * @return {?proto.solidity.uint256}
 */
proto.TestInteger.prototype.getUint256Field = function() {
  return /** @type{?proto.solidity.uint256} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint256, 6));
};


/** @param {?proto.solidity.uint256|undefined} value */
proto.TestInteger.prototype.setUint256Field = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.TestInteger.prototype.clearUint256Field = function() {
  this.setUint256Field(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.TestInteger.prototype.hasUint256Field = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional solidity.address address_field = 7;
 * @return {?proto.solidity.address}
 */
proto.TestInteger.prototype.getAddressField = function() {
  return /** @type{?proto.solidity.address} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.address, 7));
};


/** @param {?proto.solidity.address|undefined} value */
proto.TestInteger.prototype.setAddressField = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.TestInteger.prototype.clearAddressField = function() {
  this.setAddressField(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.TestInteger.prototype.hasAddressField = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional solidity.int64 int64_field = 8;
 * @return {?proto.solidity.int64}
 */
proto.TestInteger.prototype.getInt64Field = function() {
  return /** @type{?proto.solidity.int64} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.int64, 8));
};


/** @param {?proto.solidity.int64|undefined} value */
proto.TestInteger.prototype.setInt64Field = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.TestInteger.prototype.clearInt64Field = function() {
  this.setInt64Field(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.TestInteger.prototype.hasInt64Field = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional solidity.uint64 uint64_field = 9;
 * @return {?proto.solidity.uint64}
 */
proto.TestInteger.prototype.getUint64Field = function() {
  return /** @type{?proto.solidity.uint64} */ (
    jspb.Message.getWrapperField(this, SolidityTypes_pb.uint64, 9));
};


/** @param {?proto.solidity.uint64|undefined} value */
proto.TestInteger.prototype.setUint64Field = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.TestInteger.prototype.clearUint64Field = function() {
  this.setUint64Field(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.TestInteger.prototype.hasUint64Field = function() {
  return jspb.Message.getField(this, 9) != null;
};


goog.object.extend(exports, proto);
