/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SolidityTypes_pb = require('./SolidityTypes_pb.js');
goog.object.extend(proto, SolidityTypes_pb);
goog.exportSymbol('proto.TestRepeatedAdd', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TestRepeatedAdd = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.TestRepeatedAdd.repeatedFields_, null);
};
goog.inherits(proto.TestRepeatedAdd, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.TestRepeatedAdd.displayName = 'proto.TestRepeatedAdd';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.TestRepeatedAdd.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TestRepeatedAdd.prototype.toObject = function(opt_includeInstance) {
  return proto.TestRepeatedAdd.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TestRepeatedAdd} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TestRepeatedAdd.toObject = function(includeInstance, msg) {
  var f, obj = {
    uint256sList: jspb.Message.toObjectList(msg.getUint256sList(),
    SolidityTypes_pb.uint256.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TestRepeatedAdd}
 */
proto.TestRepeatedAdd.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TestRepeatedAdd;
  return proto.TestRepeatedAdd.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TestRepeatedAdd} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TestRepeatedAdd}
 */
proto.TestRepeatedAdd.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SolidityTypes_pb.uint256;
      reader.readMessage(value,SolidityTypes_pb.uint256.deserializeBinaryFromReader);
      msg.addUint256s(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TestRepeatedAdd.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TestRepeatedAdd.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TestRepeatedAdd} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TestRepeatedAdd.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUint256sList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      SolidityTypes_pb.uint256.serializeBinaryToWriter
    );
  }
};


/**
 * repeated solidity.uint256 uint256s = 1;
 * @return {!Array<!proto.solidity.uint256>}
 */
proto.TestRepeatedAdd.prototype.getUint256sList = function() {
  return /** @type{!Array<!proto.solidity.uint256>} */ (
    jspb.Message.getRepeatedWrapperField(this, SolidityTypes_pb.uint256, 1));
};


/** @param {!Array<!proto.solidity.uint256>} value */
proto.TestRepeatedAdd.prototype.setUint256sList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.solidity.uint256=} opt_value
 * @param {number=} opt_index
 * @return {!proto.solidity.uint256}
 */
proto.TestRepeatedAdd.prototype.addUint256s = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.solidity.uint256, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.TestRepeatedAdd.prototype.clearUint256sList = function() {
  this.setUint256sList([]);
};


goog.object.extend(exports, proto);
